[package]
name = "tunnelbana"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "fs"] }
hyper-util = { version = "0.1", features = ["server", "server-graceful", "server-auto", "http1", "http2",  "service"] }
tower-http = { version = "0.6", features = ["fs", "validate-request"] }
tunnelbana-tower = { workspace = true }
tracing = "0.1"
tower = { version = "0.5",  features = ["util"] }
vss = "0.1"
http = "1"
http-body-util = "0.1"
bytes = "1"
tracing-subscriber = "0.3"

[workspace]
members = ["tunnelbana-tower"]

[workspace.dependencies]
tunnelbana-tower = { path = "tunnelbana-tower" }
