[package]
name = "tunnelbana-etags"
version = "0.1.0"
edition = "2021"

[dependencies]
# blake3
blake3 = { version = "1", features = ["mmap", "rayon"] }

# http
tower = "0.5"
http = "1"
http-body = "1"
http-body-util = "0.1"
bytes = "1"

# utils
pin-project = "1"
tracing = "0.1"
thiserror = "2"