[package]
name = "tunnelbana-etags"
version = "0.2.0"
edition = "2024"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
description = "Generate etags for static files and serve them with tower."
keywords = ["etags", "caching"]
categories = ["web-programming", "caching"]
repository = "https://github.com/randomairborne/tunnelbana"
readme = "README.txt"
license = "MIT OR Apache-2.0"

[dependencies]
# blake3
blake3 = { version = "1", features = ["mmap", "rayon"] }

# http
tower = "0.5"
http = "1"
http-body = "1"
http-body-util = "0.1"
bytes = "1"

# utils
pin-project = "1"
tracing = "0.1"
thiserror = "2"

[dev-dependencies]
tower-http = { version = "0.6", features = ["fs"] }
tower = { version = "0.5", features = ["util"] }