[package]
name = "tunnelbana-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
tower = "0.5"
http = "1"
http-body = "1"
http-body-util = "0.1"
bytes = "1"
tracing = "0.1"
matchit = "0.8"
pin-project = "1"
thiserror = "1"